FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build
WORKDIR /app
# copy csproj and restore as distinct layer
COPY *.csproj ./
RUN dotnet restore WebAPIBackEnd.csproj
# copy everything else and build app
COPY . ./
RUN dotnet publish WebAPIBackEnd.csproj -c Release -o out
FROM mcr.microsoft.com/dotnet/core/aspnet:2.2 AS runtime
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT ["dotnet", "WebAPIBackEnd.dll"]